services:
  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./Frontend
    ports:
      - "8501:8501"
    volumes:
      - ./Frontend:/app
    depends_on:
      - backend
